os: osx
language: go

go:
  - 1.11.x

cache:
  directories:
    - $HOME/Library/Caches/go-build
    - $HOME/gopath/pkg/mod

branches:
  only: master

env:
  global:
    - GO111MODULE=on

install: true

jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: test
      before_script: go get
      script: go test -v ./cmd

stages:
  - prepare cache
  - test
